"""
Specific error codes to raise
"""

NOT_AUTHENTICATED = "not_authenticated"
INVALID_INPUT_DATA = "invalid_input_data"
INVALID_OTP = "invalid_otp"
NOT_FOUND = "not_found"
OTP_RESEND_TIME_LIMIT = "otp_resend_time_limit"
TOO_MANY_REQUEST = "too_many_request"
INTERNAL_SERVER_ERROR = "internal_server_error"
ACCESS_DENIED = "access_denied"
TOKEN_EXPIRED = "token_expired"
USER_INACTIVE = "user_inactive"
INVALID_REFRESH_TOKEN = "invalid_refresh_token"
USER_ALREADY_EXISTS = "user_already_exists"
USER_ALREADY_HAS_ACTIVE_BOOKING = "user_already_has_active_booking"
USER_NOT_FOUND = "user_not_found"
USER_NOT_AUTHORIZED = "user_not_authorized"
USER_DOES_NOT_HAVE_PHONE_NUMBER = "user_does_not_have_phone_number"
PASSWORD_MIN_LENGTH = "password_min_length"
PASSWORDS_ARE_NOT_EQUAL = "passwords_are_not_equal"
PASSWORD_INVALID = "password_invalid"
EMAIL_CONFIRMATION_EXPIRED = "email_confirmation_expired"
EMAIL_ALREADY_CONFIRMED = "email_already_confirmed"
CLUB_BRANCH_NOT_FOUND = "club_branch_not_found"
COMPUTER_DOES_NOT_BELONG_TO_CLUB_BRANCH = "computer_does_not_belong_to_club_branch"
COMPUTER_IS_ALREADY_BOOKED = "COMPUTER_IS_ALREADY_BOOKED"
GIZMO_REQUEST_ERROR = "gizmo_request_error"
BOOKING_NOT_FOUND = "booking_not_found"
NEED_TO_INPUT_USER_LOGIN = "NEED_TO_INPUT_USER_LOGIN"
NEED_TO_INPUT_USER_MOBILE_PHONE = "NEED_TO_INPUT_USER_MOBILE_PHONE"
GIZMO_LOGIN_ALREADY_EXISTS_ERROR = "gizmo_login_already_exists_error"
BOOKING_STATUS_IS_NOT_APPROPRIATE = "booking_status_is_not_appropriate"
USER_NEED_TO_VERIFY_IIN = "USER_NEED_TO_VERIFY_IIN"
ONEVISION_SERVICE_INPUT_DATA_INVALID = "onevision_service_input_data_invalid"
NOT_APPROVED_USER_CAN_NOT_BOOK_SEVERAL_COMPUTERS= "not_approved_user_can_not_book_several_computers"
NOT_SUFFICIENT_CASHBACK_AMOUNT = "NOT_SUFFICIENT_CASHBACK_AMOUNT"
