# Generated by Django 4.0 on 2024-10-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
    ]
