# Generated by Django 4.0 on 2024-10-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_banner_coursefeature_userchampion_userreview_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
