# Generated by Django 4.0 on 2024-10-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_userreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='features',
            field=models.ManyToManyField(to='landing.CourseFeature'),
        ),
    ]
