# Generated by Django 4.1.7 on 2024-07-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_school_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['priority'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['priority'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['priority'], 'verbose_name': 'Direction', 'verbose_name_plural': 'Directions'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['priority'], 'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['priority'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['priority'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
