# Generated by Django 4.0 on 2024-07-26 16:19

from django.db import migrations
import localized_fields.fields.char_field
import localized_fields.fields.text_field


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_chapter_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(null=True, required=['ru'], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(null=True, required=['ru'], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='description',
            field=localized_fields.fields.text_field.LocalizedTextField(null=True, required=['ru'], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(null=True, required=['ru'], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(null=True, required=['ru'], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(null=True, required=['ru'], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=localized_fields.fields.char_field.LocalizedCharField(null=True, required=['ru'], verbose_name='Название'),
        ),
    ]
