# Generated by Django 4.0 on 2024-07-31 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_course_subject_alter_subject_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='content.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='content.chapter', verbose_name='Раздел'),
        ),
    ]
