# Generated by Django 4.0 on 2024-08-01 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('content', '0006_alter_chapter_course_alter_topic_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='location.city', verbose_name='Город'),
        ),
    ]
