# Generated by Django 4.0 on 2024-09-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_subject_enable_sor_sosh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='enable_sor_sosh',
            new_name='enable_sor_soch',
        ),
        migrations.AddField(
            model_name='subject',
            name='soch_question_count',
            field=models.IntegerField(default=0, verbose_name='СОЧ(Суммативное Оценивание за Четверть) кол-во'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sor_question_count',
            field=models.IntegerField(default=0, verbose_name='СОР(Суммативное Оценивание за Раздел) кол-во'),
        ),
    ]
