# Generated by Django 4.0 on 2024-10-08 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_rename_enable_sor_sosh_subject_enable_sor_soch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.chapter', verbose_name='Раздел'),
        ),
    ]
