# Generated by Django 4.0 on 2024-11-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_topic_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='soch_duration',
            field=models.IntegerField(default=1, verbose_name='СОЧ(Суммативное Оценивание за Четверть) длительность(минут)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sor_duration',
            field=models.IntegerField(default=1, verbose_name='СОР(Суммативное Оценивание за Раздел) длительность(минут)'),
        ),
    ]
