# Generated by Django 4.0 on 2024-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mytopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
