# Generated by Django 4.0 on 2024-08-15 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_explanation_of_answer_question_explanation_answer_and_more'),
        ('users', '0007_userquizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizquestion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_questions', to='analytics.answeroption'),
        ),
    ]
