# Generated by Django 4.0 on 2024-08-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userquizquestion_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquizquestion',
            options={'ordering': ['id']},
        ),
    ]
