# Generated by Django 4.0 on 2024-08-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_entranceexamsubject_examansweroption_examquestion_and_more'),
        ('users', '0010_remove_userquizquestion_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizquestion',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='user_quiz_questions', to='analytics.AnswerOption'),
        ),
    ]
