# Generated by Django 4.0 on 2024-08-20 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_entranceexamsubject_examansweroption_examquestion_and_more'),
        ('users', '0011_alter_userquizquestion_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answers', models.ManyToManyField(blank=True, related_name='user_exam_questions', to='analytics.ExamAnswerOption')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_questions', to='analytics.examquestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_questions', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
