# Generated by Django 4.0 on 2024-08-27 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_remove_entranceexamsubject_day_and_more'),
        ('users', '0012_userexamquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexamquestion',
            name='entrance_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_questions', to='analytics.entranceexam'),
        ),
        migrations.CreateModel(
            name='UserExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('start_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время начала')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('correct_score', models.IntegerField(default=0)),
                ('entrance_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_results', to='analytics.entranceexam', verbose_name='Выступительный тест')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_results', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
