# Generated by Django 4.0 on 2024-08-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_direction_enable_all'),
        ('users', '0013_userexamquestion_entrance_exam_userexamresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytopic',
            name='course',
        ),
        migrations.AddField(
            model_name='mytopic',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_topics', to='content.topic'),
            preserve_default=False,
        ),
    ]
