# Generated by Django 4.0 on 2024-09-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_examquestion_score'),
        ('content', '0010_direction_enable_all'),
        ('users', '0015_mytopic_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_entrance_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='analytics.entranceexam'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='content.topic'),
        ),
    ]
