# Generated by Django 4.0 on 2024-09-04 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_direction_enable_all'),
        ('users', '0017_remove_user_current_entrance_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytopic',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_topic', to='content.course'),
        ),
    ]
