# Generated by Django 4.0 on 2024-09-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_question_type'),
        ('users', '0018_mytopic_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytopic',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='userexamresult',
            name='exam_per_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_results', to='analytics.entranceexamperday', verbose_name='Выступительный тест по дням'),
        ),
    ]
