# Generated by Django 4.0 on 2024-09-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_userexamresult_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[("('male', 'Мужской')", 'Male'), ('female', 'Женский')], default="('male', 'Мужской')", max_length=20, verbose_name='Язык')),
                ('image', models.ImageField(upload_to='images/users/', verbose_name='Смайлик')),
            ],
            options={
                'verbose_name': 'Аватарка',
                'verbose_name_plural': 'Аватары',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.avatar'),
        ),
    ]
