# Generated by Django 4.0 on 2024-09-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_avatar_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'ordering': ('gender',), 'verbose_name': 'Аватарка', 'verbose_name_plural': 'Аватары'},
        ),
    ]
