# Generated by Django 4.0 on 2024-09-20 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_entranceexamperday_exam'),
        ('users', '0023_alter_avatar_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizquestion',
            name='answer_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userquizquestion',
            name='used_hints',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserQuizReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('finished', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_reports', to='analytics.quiz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_reports', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userquizquestion',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_questions', to='users.userquizreport'),
        ),
    ]
