# Generated by Django 4.0 on 2024-09-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_userquizquestion_answer_viewed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquizreport',
            options={'ordering': ['-created_at']},
        ),
    ]
