# Generated by Django 4.0 on 2024-09-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_userquizreport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizquestion',
            name='user_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
