# Generated by Django 4.0 on 2024-09-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_direction_enable_all'),
        ('users', '0026_userquizquestion_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled_courses',
            field=models.ManyToManyField(blank=True, related_name='enabled_courses', to='content.Course', verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='user',
            name='enabled_topics',
            field=models.ManyToManyField(blank=True, related_name='enabled_topics', to='content.Topic', verbose_name='Users'),
        ),
    ]
