# Generated by Django 4.0 on 2024-09-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_direction_enable_all'),
        ('users', '0027_user_enabled_courses_user_enabled_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enabled_courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', to='content.Course', verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enabled_topics',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', to='content.Topic', verbose_name='Users'),
        ),
    ]
