# Generated by Django 4.0 on 2024-09-26 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_question_level'),
        ('content', '0011_subject_enable_sor_sosh'),
        ('users', '0028_alter_user_enabled_courses_alter_user_enabled_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('1', '1 четверть'), ('2', '2 четверть'), ('3', '3 четверть'), ('4', '4 четверть')], default='1', max_length=10, verbose_name='Четверть')),
                ('assessment_type', models.CharField(choices=[('SOR', 'Суммативное Оценивание за Раздел (СОР)'), ('SOCH', 'Суммативное Оценивание за Четверть (СОЧ)')], max_length=4, verbose_name='Тип оценивания')),
                ('level', models.IntegerField(default=1)),
                ('start_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время начала')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('is_finished', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='content.chapter', verbose_name='Раздел')),
                ('questions', models.ManyToManyField(to='analytics.Question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='content.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='UserAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answers', models.ManyToManyField(blank=True, related_name='user_assessment_results', to='analytics.AnswerOption')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assessment_results', to='users.userassessment', verbose_name='Сор/Соч')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assessment_results', to='analytics.question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assessment_results', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
