# Generated by Django 4.0 on 2024-09-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_userassessment_course_userassessment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassessment',
            name='quarter',
            field=models.CharField(blank=True, choices=[('1', '1 четверть'), ('2', '2 четверть'), ('3', '3 четверть'), ('4', '4 четверть')], max_length=10, null=True, verbose_name='Четверть'),
        ),
    ]
