# Generated by Django 4.0 on 2024-09-27 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_userassessment_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
