# Generated by Django 4.0 on 2024-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_userassessment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessmentresult',
            name='user_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
