# Generated by Django 4.0 on 2024-10-01 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_diagnosticexamquestion_diagnosticexamansweroption_and_more'),
        ('users', '0033_userassessmentresult_user_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiagnosticsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('user_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answers', models.ManyToManyField(blank=True, related_name='user_diagnostic_results', to='analytics.DiagnosticExamAnswerOption')),
                ('diagnostic_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_diagnostic_results', to='analytics.diagnosticexam', verbose_name='Диагностический тест')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_diagnostic_results', to='analytics.diagnosticexamquestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_diagnostic_results', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
