# Generated by Django 4.0 on 2024-10-02 20:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_remove_diagnosticexam_subject_and_more'),
        ('users', '0034_userdiagnosticsresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdiagnosticsresult',
            name='diagnostic_exam',
        ),
        migrations.CreateModel(
            name='UserDiagnosticExamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('questions', models.ManyToManyField(blank=True, related_name='user_diagnostic_reports', to='analytics.DiagnosticExamQuestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_diagnostic_reports', to='users.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='userdiagnosticsresult',
            name='user_diagnostic_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_diagnostic_results', to='users.userdiagnosticexamreport', verbose_name='Диагностический тест'),
        ),
    ]
