# Generated by Django 4.0 on 2024-10-02 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_remove_diagnosticexam_subject_and_more'),
        ('users', '0035_remove_userdiagnosticsresult_diagnostic_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiagnosticexamreport',
            name='diagnostic_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_diagnostic_reports', to='analytics.diagnosticexam', verbose_name='Диагностический тест'),
        ),
        migrations.AlterField(
            model_name='userdiagnosticsresult',
            name='user_diagnostic_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_diagnostic_results', to='users.userdiagnosticexamreport', verbose_name='Репорт'),
        ),
    ]
