# Generated by Django 4.0 on 2024-10-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_userdiagnosticexamreport_diagnostic_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
