# Generated by Django 4.0 on 2024-11-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_userexamquestion_exam_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения'),
        ),
    ]
