# Generated by Django 4.0 on 2024-11-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_userassessment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexamquestion',
            name='user_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
