# Generated by Django 4.0 on 2024-11-15 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_userexamresult_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexamresult',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
