# Generated by Django 4.0 on 2024-08-01 16:12

from django.db import migrations, models
import localized_fields.fields.char_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', localized_fields.fields.char_field.LocalizedCharField(blank=True, null=True, required=[], verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('name__ru',),
            },
        ),
    ]
