from .base import *

FCM_CREDENTIALS_PATH = "/credentials/fcm-prod.json"

REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")
CONSTANCE_REDIS_CONNECTION = REDIS_AS_CACHE_URL
CACHES['default']['LOCATION'] = REDIS_AS_CACHE_URL
CELERY_BROKER_URL = REDIS_AS_BROKER_URL
