# Generated by Django 4.0 on 2024-08-15 16:42

from django.db import migrations, models
import django.db.models.deletion
import localized_fields.fields.char_field
import localized_fields.fields.file_field
import localized_fields.fields.text_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0009_alter_chapter_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='content.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Вступительный тест',
                'verbose_name_plural': 'Вступительные тесты',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('simulator', 'Тренажер'), ('diagnostic', 'Диогностически')], default='simulator', max_length=255, verbose_name='Тип теста')),
                ('questions_amount', models.IntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='content.course', verbose_name='Курс')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='content.subject', verbose_name='Предмет')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='content.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', localized_fields.fields.char_field.LocalizedCharField(blank=True, null=True, required=[], verbose_name='Заголовок')),
                ('image', localized_fields.fields.file_field.LocalizedFileField(blank=True, null=True, required=[], upload_to='images/analytics/', verbose_name='Картинка')),
                ('explain_video', localized_fields.fields.text_field.LocalizedTextField(blank=True, null=True, required=[], verbose_name='Объяснительное видео')),
                ('type', models.CharField(choices=[('one_choice', 'Выбрать один'), ('multiple_choice', 'Выбрать несколько')], default='one_choice', max_length=255, verbose_name='Тип вопроса')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='analytics.quiz', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', localized_fields.fields.char_field.LocalizedCharField(blank=True, null=True, required=[], verbose_name='Заголовок')),
                ('max_score', models.IntegerField(verbose_name='Максимальное количество баллов')),
                ('questions_amount', models.IntegerField(verbose_name='Количество вопросов')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_subjects', to='analytics.assessment', verbose_name='Выступительный тест')),
            ],
            options={
                'verbose_name': 'Вступительный тест по предметом',
                'verbose_name_plural': 'Вступительные тесты по предметом',
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', localized_fields.fields.char_field.LocalizedCharField(blank=True, null=True, required=[], verbose_name='Заголовок')),
                ('image', localized_fields.fields.file_field.LocalizedFileField(blank=True, null=True, required=[], upload_to='images/analytics/', verbose_name='Картинка')),
                ('assessment_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='analytics.assessmentsubject', verbose_name='Вступительный тест по предметом')),
            ],
            options={
                'verbose_name': 'Вопрос (Вступительный тест)',
                'verbose_name_plural': 'Вопросы (Вступительный тест)',
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', localized_fields.fields.text_field.LocalizedTextField(blank=True, null=True, required=[], verbose_name='Текст')),
                ('image', localized_fields.fields.file_field.LocalizedFileField(blank=True, null=True, required=[], upload_to='images/analytics/', verbose_name='Картинка')),
                ('is_correct', models.BooleanField(default=False)),
                ('assessment_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_answer_options', to='analytics.assessmentquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', localized_fields.fields.text_field.LocalizedTextField(blank=True, null=True, required=[], verbose_name='Текст')),
                ('image', localized_fields.fields.file_field.LocalizedFileField(blank=True, null=True, required=[], upload_to='images/analytics/', verbose_name='Картинка')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_options', to='analytics.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
                'abstract': False,
            },
        ),
    ]
