# Generated by Django 4.0 on 2024-08-15 19:30

from django.db import migrations
import localized_fields.fields.text_field


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_of_answer',
            field=localized_fields.fields.text_field.LocalizedTextField(blank=True, null=True, required=[], verbose_name='Объяснение ответа'),
        ),
    ]
