# Generated by Django 4.0 on 2024-08-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_explanation_of_answer_question_explanation_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
