# Generated by Django 4.0 on 2024-08-16 18:38

from django.db import migrations, models
import django.db.models.deletion
import localized_fields.fields.char_field
import localized_fields.fields.file_field
import localized_fields.fields.text_field


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_chapter_quarter'),
        ('analytics', '0006_alter_assessmentsubject_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', localized_fields.fields.char_field.LocalizedCharField(blank=True, null=True, required=[], verbose_name='Заголовок')),
                ('max_score', models.IntegerField(verbose_name='Максимальное количество баллов')),
                ('questions_amount', models.IntegerField(verbose_name='Количество вопросов')),
                ('day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=100, verbose_name='Какой день')),
            ],
            options={
                'verbose_name': 'Вступительный тест по предметом',
                'verbose_name_plural': 'Вступительные тесты по предметом',
            },
        ),
        migrations.CreateModel(
            name='ExamAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', localized_fields.fields.text_field.LocalizedTextField(blank=True, null=True, required=[], verbose_name='Текст')),
                ('image', localized_fields.fields.file_field.LocalizedFileField(blank=True, null=True, required=[], upload_to='images/analytics/', verbose_name='Картинка')),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', localized_fields.fields.char_field.LocalizedCharField(blank=True, null=True, required=[], verbose_name='Заголовок')),
                ('image', localized_fields.fields.file_field.LocalizedFileField(blank=True, null=True, required=[], upload_to='images/analytics/', verbose_name='Картинка')),
                ('assessment_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_questions', to='analytics.entranceexamsubject', verbose_name='Вступительный тест по предметом')),
            ],
            options={
                'verbose_name': 'Вопрос (Вступительный тест)',
                'verbose_name_plural': 'Вопросы (Вступительный тест)',
            },
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='assessment_subject',
        ),
        migrations.RemoveField(
            model_name='assessmentsubject',
            name='assessment',
        ),
        migrations.RenameModel(
            old_name='Assessment',
            new_name='EntranceExam',
        ),
        migrations.DeleteModel(
            name='AssessmentAnswerOption',
        ),
        migrations.DeleteModel(
            name='AssessmentQuestion',
        ),
        migrations.DeleteModel(
            name='AssessmentSubject',
        ),
        migrations.AddField(
            model_name='examansweroption',
            name='exam_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_answer_options', to='analytics.examquestion', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='entranceexamsubject',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_subjects', to='analytics.entranceexam', verbose_name='Выступительный тест'),
        ),
    ]
