# Generated by Django 4.0 on 2024-08-27 20:37

from django.db import migrations, models
import django.db.models.deletion
import localized_fields.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_entranceexamsubject_examansweroption_examquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entranceexamsubject',
            name='day',
        ),
        migrations.RemoveField(
            model_name='entranceexamsubject',
            name='exam',
        ),
        migrations.CreateModel(
            name='EntranceExamPerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', localized_fields.fields.char_field.LocalizedCharField(blank=True, null=True, required=[], verbose_name='Заголовок')),
                ('passing_score', models.IntegerField(verbose_name='Проходной балл')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_per_day', to='analytics.entranceexam', verbose_name='Выступительный тест')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='entranceexamsubject',
            name='exam_per_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_subjects', to='analytics.entranceexamperday', verbose_name='День'),
        ),
    ]
