# Generated by Django 4.0 on 2024-08-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_remove_entranceexamsubject_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
