# Generated by Django 4.0 on 2024-09-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_examquestion_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('one_choice', 'Выбрать один'), ('open_answer', 'Open answer'), ('multiple_choice', 'Выбрать несколько')], default='one_choice', max_length=255, verbose_name='Тип вопроса'),
        ),
    ]
