# Generated by Django 4.0 on 2024-09-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_question_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['score'], 'verbose_name': 'Вопрос (Вступительный тест)', 'verbose_name_plural': 'Вопросы (Вступительный тест)'},
        ),
    ]
