# Generated by Django 4.0 on 2024-09-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_alter_examquestion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entranceexamperday',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_per_day', to='analytics.entranceexam', verbose_name='Выступительный тест'),
        ),
    ]
