# Generated by Django 4.0 on 2024-10-01 20:04

from django.db import migrations, models
import django.db.models.deletion
import localized_fields.fields.char_field
import localized_fields.fields.file_field
import localized_fields.fields.text_field


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_rename_enable_sor_sosh_subject_enable_sor_soch_and_more'),
        ('analytics', '0014_question_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', localized_fields.fields.char_field.LocalizedCharField(blank=True, null=True, required=[], verbose_name='Заголовок')),
                ('image', localized_fields.fields.file_field.LocalizedFileField(blank=True, null=True, required=[], upload_to='images/analytics/', verbose_name='Картинка')),
                ('score', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Вопрос (Диагностический тест)',
                'verbose_name_plural': 'Вопросы (Диагностический тест)',
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticExamAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', localized_fields.fields.text_field.LocalizedTextField(blank=True, null=True, required=[], verbose_name='Текст')),
                ('image', localized_fields.fields.file_field.LocalizedFileField(blank=True, null=True, required=[], upload_to='images/analytics/', verbose_name='Картинка')),
                ('is_correct', models.BooleanField(default=False)),
                ('diagnostic_exam_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_exam_answer_options', to='analytics.diagnosticexamquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', localized_fields.fields.char_field.LocalizedCharField(blank=True, null=True, required=[], verbose_name='Заголовок')),
                ('enabled', models.BooleanField(default=True, verbose_name='Разрешен')),
                ('questions_amount', models.IntegerField(default=1, verbose_name='Количество вопросов')),
                ('duration', models.IntegerField(default=1, verbose_name='Длительность(минут)')),
                ('questions', models.ManyToManyField(to='analytics.DiagnosticExamQuestion', verbose_name='Вопросы')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_exams', to='content.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Диагностический тест',
                'verbose_name_plural': 'Диагностический тесты',
            },
        ),
    ]
