# Generated by Django 4.0 on 2024-10-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_rename_enable_sor_sosh_subject_enable_sor_soch_and_more'),
        ('analytics', '0016_remove_diagnosticexam_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticexam',
            name='subject',
        ),
        migrations.AddField(
            model_name='diagnosticexamquestion',
            name='grade',
            field=models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], default='1', max_length=3, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='diagnosticexamquestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_exams', to='content.topic', verbose_name='Тема'),
        ),
    ]
