# Generated by Django 4.0 on 2024-10-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_remove_diagnosticexam_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticexamquestion',
            name='type',
            field=models.CharField(choices=[('one_choice', 'Выбрать один'), ('open_answer', 'Open answer'), ('multiple_choice', 'Выбрать несколько')], default='one_choice', max_length=255, verbose_name='Тип вопроса'),
        ),
    ]
