# Generated by Django 4.0 on 2024-11-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_diagnosticexamquestion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entranceexamperday',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Длительность(в сек)'),
        ),
    ]
