# Generated by Django 4.0 on 2024-11-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_alter_entranceexamperday_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='type',
            field=models.CharField(choices=[('one_choice', 'Выбрать один'), ('open_answer', 'Open answer'), ('multiple_choice', 'Выбрать несколько')], default='one_choice', max_length=255, verbose_name='Тип вопроса'),
        ),
    ]
