# Generated by Django 4.0 on 2024-11-11 20:13

from django.db import migrations
import localized_fields.fields.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0021_examquestion_explanation_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='explanation_answer_image',
            field=localized_fields.fields.file_field.LocalizedFileField(blank=True, null=True, required=[], upload_to='images/analytics/', verbose_name='Объяснение ответа(картинка)'),
        ),
    ]
