# Generated by Django 4.0 on 2025-01-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0024_diagnosticbotsession_diagnosticbotuseranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticbotsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2025-01-01', verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
