# Generated by Django 4.0 on 2025-01-15 13:40

from django.db import migrations
import localized_fields.fields.text_field


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0025_diagnosticbotsession_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticexamquestion',
            name='title',
            field=localized_fields.fields.text_field.LocalizedTextField(blank=True, null=True, required=[], verbose_name='Заголовок'),
        ),
    ]
